export const FETCH_USER_INPROGRESS = "FETCH_USER_INPROGRESS";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const FETCH_ALLTASK_INPROGRESS = "FETCH_ALLTASK_INPROGRESS";
export const FETCH_ALLTASK_SUCCESS = "FETCH_ALLTASK_SUCCESS";
export const FETCH_ALLTASK_ERROR = "FETCH_ALLTASK_ERROR";

export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const ERROR = "ERROR";
